// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BindCard: typeof import('./src/components/member/bind-card.vue')['default']
    Contract: typeof import('./src/components/market/contract.vue')['default']
    Copyright: typeof import('./src/components/plugins/copyright/index.vue')['default']
    CreateOrder: typeof import('./src/components/member/order/create-order.vue')['default']
    DetailModal: typeof import('./src/components/member/detail-modal.vue')['default']
    Icon: typeof import('./src/components/select-modal/icon/index.vue')['default']
    ImgCropper: typeof import('./src/components/plugins/img-cropper/index.vue')['default']
    LayoutBody: typeof import('./src/components/layouts/LayoutBody.vue')['default']
    LayoutBodyContent: typeof import('./src/components/layouts/LayoutBodyContent.vue')['default']
    LayoutBodyTabs: typeof import('./src/components/layouts/LayoutBodyTabs.vue')['default']
    LayoutNav: typeof import('./src/components/layouts/LayoutNav.vue')['default']
    Layouts: typeof import('./src/components/layouts/index.vue')['default']
    Login: typeof import('./src/components/member/login.vue')['default']
    LoginArtical: typeof import('./src/components/member/login-artical.vue')['default']
    MarketDetail: typeof import('./src/components/market/market-detail.vue')['default']
    MarketEcharts: typeof import('./src/components/market/market-echarts.vue')['default']
    MarketItemPriceChange: typeof import('./src/components/market/market-item-price-change.vue')['default']
    MemberNavCoin: typeof import('./src/components/member/member-nav-coin.vue')['default']
    Order: typeof import('./src/components/member/order.vue')['default']
    OrderComplate: typeof import('./src/components/member/order/order-complate.vue')['default']
    OrderDetail: typeof import('./src/components/member/order/order-detail.vue')['default']
    OrderHistoryRecord: typeof import('./src/components/member/order/order-history-record.vue')['default']
    OrderHold: typeof import('./src/components/member/order/order-hold.vue')['default']
    OrderItemYingkui: typeof import('./src/components/member/order/order-item-yingkui.vue')['default']
    OrderRobot: typeof import('./src/components/member/order/order-robot.vue')['default']
    OrderSetRobot: typeof import('./src/components/member/order/order-set-robot.vue')['default']
    Page: typeof import('./src/components/plugins/page/index.vue')['default']
    RechargeModal: typeof import('./src/components/member/recharge-modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sector: typeof import('./src/components/market/sector.vue')['default']
    ShortcutsTime: typeof import('./src/components/plugins/shortcuts-time/index.vue')['default']
    UpdatePassword: typeof import('./src/components/member/update-password.vue')['default']
    Wallet: typeof import('./src/components/member/wallet.vue')['default']
    Water: typeof import('./src/components/member/water.vue')['default']
  }
}
